package com.example.login.entity;

import com.example.login.R;

import java.util.ArrayList;
import java.util.List;

public class DataService {

    public static List<ProductInfo> getListData(int position) {
        List<ProductInfo> list = new ArrayList<>();
        if (position == 0) {
            list.add(new ProductInfo(0, "Wolverine", R.mipmap.wolf, 8.5, "Hugh Jackman, Liev Schreiber, Ryan Reynolds, Lynn Collins, Danny Huston, Taylor Kitsch, Will i Am, Daniel Henney, Kevin Durand",
                    "Fantasy|Sci-Fi|Action", "2009-05-03", "United States", "The film is adapted from Marvel Comics and serves as a prequel to the X-Men series, set before the events of the first X-Men movie. It explores the past and present of the X-Men core member Wolverine, delving into his relationships with his brother Sabretooth, his girlfriend Silver Fox, and the Weapon X program.", 50));
            list.add(new ProductInfo(1, "Cold War", R.mipmap.cold, 8.9, "Directed and written by Sunny Luk and Felix Chong, starring Aaron Kwok, Tony Leung, Aarif Rahman, Eddie Peng, Ma Yili, Andy Lau, Qian Jiale",
                    "Action|Drama|Crime", "2012-11-08", "Hong Kong, China", "The film tells the story of a police van and five officers being hijacked in Hong Kong, known as the 'safest city.' This incident plunges the city into a security crisis, triggering a power struggle within the police force and a high-stakes intellectual battle between the police and criminals.", 30));
            list.add(new ProductInfo(2, "Shadow", R.mipmap.shadow, 7.8, "Deng Chao, Sun Li, Zheng Kai, Wang Qianyuan, Hu Jun, Wang Jingchun, Guan Xiaotong, Wu Lei",
                    "Drama|Action|Martial Arts", "2018-09-30", "Mainland China", "The film tells the story of a man secretly imprisoned since the age of eight, unwilling to be merely a puppet or a weapon in someone else's hands. To break free and reclaim his true self, he must overcome countless challenges. The story revolves around this stand-in's struggle for freedom and the difficulties he encounters along the way.", 60));
            list.add(new ProductInfo(3, "Casino Royale", R.mipmap.tegong, 6.8, "Written by Neal Purvis, Robert Wade, Paul Haggis, starring Daniel Craig, Eva Green, Mads Mikkelsen",
                    "Action|Adventure|Thriller", "2006-11-17", "United States", "The 21st film in the James Bond series produced by MGM, adapted from Ian Fleming's first Bond novel published in 1953. It marks Daniel Craig's debut as the sixth James Bond, telling the story of a newly minted British agent. Despite being a rookie, Bond already possesses exceptional spy skills, completing two professional assassinations and earning his '007' status.", 20));
            list.add(new ProductInfo(4, "The Grave Robbers' Chronicles", R.mipmap.daomu, 8.8, "Jing Boran, Lu Han, Wang Jingchun, Ma Sichun",
                    "Mystery|Fantasy|Adventure", "2016-08-05", "Mainland China", "Adapted from Nanpai Sanshu's novel of the same name, the film follows Wu Xie, an enthusiast of ancient architecture, as he embarks on an unprecedented adventure under the guidance of his uncle, alongside Zhang Qiling, An Ning, Pan Zi, and Fatty Wang.", 40));
            list.add(new ProductInfo(5, "Deadpool", R.mipmap.sishi, 8.5, "Ryan Reynolds, Morena Baccarin, Ed Skrein, Gina Carano",
                    "Sci-Fi|Action|Crime|Romance", "2016-02-12", "United States", "Adapted from the Marvel Comics character, this film is a spin-off of the X-Men series. It follows Wade Wilson, a former special forces operative diagnosed with cancer, who is kidnapped by an unknown organization to test mutant genes. After enduring brutal torture, he escapes and seeks revenge on Ajax, the man who turned him into a mutant.", 40));

        } else if (position == 1) {
            list.add(new ProductInfo(61, "Coco", R.mipmap.img_61, 9.9, "Anthony Gonzalez, Benjamin Bratt, Gael García Bernal, Renee Victor",
                    "Comedy|Animation|Music|Fantasy", "2017-11-22", "United States", "Inspired by the Mexican Day of the Dead, the film follows a music-loving boy named Miguel and a down-on-his-luck musician, Héctor, as they embark on an extraordinary adventure in a vibrant, mysterious world.", 65));
            list.add(new ProductInfo(62, "Fighter", R.mipmap.img_62, 8.1, "Nick Cheung, Eddie Peng, Mei Ting",
                    "Action|Drama", "2013-08-16", "Hong Kong, China", "The film tells the story of two men—one fleeing debt, the other searching for his father—who meet in Macau and become mentor and apprentice in boxing. They step into the MMA ring to face formidable opponents for their own goals.", 35));
            list.add(new ProductInfo(63, "The Wandering Earth", R.mipmap.img_63, 9.9, "Qu Chuxiao, Li Guangjie, Wu Mengda, Zhao Jinmai, Wu Jing",
                    "Sci-Fi|Adventure|Disaster", "2019-02-05", "Mainland China", "Adapted from Liu Cixin's novel of the same name, set in 2075, the film depicts a dying sun and an uninhabitable solar system. Humanity launches the 'Wandering Earth' project to move the planet out of the solar system in search of a new home.", 75));
            list.add(new ProductInfo(64, "Joker", R.mipmap.img_64, 8.8, "Directed by Todd Phillips, written by Todd Phillips and Scott Silver, starring Joaquin Phoenix",
                    "Drama|Thriller|Crime", "2019-10-04", "United States", "Adapted from the DC Comics supervillain, the film follows Arthur, a struggling comedian in the 1980s, who descends into madness and begins a criminal career in Gotham City, becoming Batman's archenemy, the Joker.", 30));
            list.add(new ProductInfo(65, "Deep Sea", R.mipmap.img_65, 8.8, "Directed by Tian Xiaopeng, written by Tian Xiaopeng and Tian Bo, voiced by Su Xin, Wang Tingwen, Teng Kuixing",
                    "Animation", "2023-01-22", "Mainland China", "The film follows a girl named Shenxiu as she explores a mysterious underwater world, meeting Captain Nanhe and embarking on a unique journey of self-discovery.", 52));
            list.add(new ProductInfo(66, "Detective Chinatown 3", R.mipmap.img_66, 8.3, "Directed by Chen Sicheng, starring Wang Baoqiang, Liu Haoran, Satoshi Tsumabuki, Tony Jaa, Masami Nagasawa",
                    "Action|Mystery|Comedy", "2021-02-12", "Mainland China", "The third installment of the Detective Chinatown series follows Tang Ren and Qin Feng, invited by Noda Hao to investigate a locked-room murder in Tokyo, Japan, after solving cases in Bangkok and New York.", 42));
            list.add(new ProductInfo(67, "Flipped", R.mipmap.img_67, 9.7, "Directed by Rob Reiner, written by Andrew Scheinman, starring Madeline Carroll, Callan McAuliffe",
                    "Comedy|Romance|Drama|Family|Classic", "2010-07-26", "Hong Kong, China", "Adapted from Wendelin Van Draanen's novel, the film portrays the innocent and pure romance between Juli Baker and Bryce Loski, focusing on their emotional growth and evolving relationship from second grade to eighth grade.", 58));
        } else if (position == 2) {
            list.add(new ProductInfo(70, "Andhadhun", R.mipmap.img_70, 8.9, "Directed by Sriram Raghavan, written by Olivier Treiner, Arijit Biswas, Yogesh Chandekar, starring Ayushmann Khurrana, Tabu, Radhika Apte, Anil Dhawan",
                    "Comedy|Mystery|Thriller|Crime", "2019-04-03", "Mainland China", "Inspired by the 2010 French short film of the same name, the story follows Akash, a piano tuner pretending to be blind, who becomes an unexpected 'witness' to a murder and faces a series of unpredictable events.", 61));
            list.add(new ProductInfo(71, "The Truman Show", R.mipmap.img_71, 9.5, "Written by Andrew Niccol, directed by Peter Weir, starring Jim Carrey, Laura Linney, Noah Emmerich, Ed Harris",
                    "Drama|Sci-Fi|Comedy", "1998-06-05", "Mainland China", "The film follows Truman, the star of a popular soap opera, unaware that his entire life, including his friends and family, is staged, and he is surrounded by actors.", 68));
            list.add(new ProductInfo(72, "Dangal", R.mipmap.img_72, 8.9, "Directed by Nitesh Tiwari, written by Piyush Gupta, Shreyas Jain, Nikhil Mehrotra, starring Aamir Khan, Sakshi Tanwar",
                    "Drama|Family|Biography|Sports", "2016-12-23", "India", "Based on the true story of Indian wrestler Mahavir Singh Phogat, the film follows his dream of winning a gold medal for India. Despite having four daughters, he discovers the wrestling talent in Babita Kumari Phogat and Geeta Phogat, training them to become local champions.", 60));
            list.add(new ProductInfo(73, "Dying to Survive", R.mipmap.img_73, 7.8, "Written by Han Jianv, directed by Wen Muye, produced by Ning Hao and Xu Zheng, starring Xu Zheng, Zhou Yiwei, Wang Chuanjun, Tan Zhuo, Zhang Yu, Yang Xinming, Wang Yanhui, with Li Naiwen and Gong Beibi in cameo roles",
                    "Medical Drama", "2018-07-05", "Mainland China", "Based on true events, the film follows Cheng Yong, a struggling health supplement vendor unable to pay rent, who becomes the exclusive agent for an Indian generic drug, 'Gleevec,' transforming his life.", 50));
            list.add(new ProductInfo(74, "The Pursuit of Happyness", R.mipmap.img_74, 9.7, "Directed by Gabriele Muccino, written by Steve Conrad, starring Will Smith, Jaden Smith, Thandiwe Newton",
                    "Drama|Family|Biography", "2006-12-15", "United States", "Based on the true story of investment expert Chris Gardner, the film follows a struggling salesman facing bankruptcy and abandonment by his wife, who works tirelessly as a single parent to become a stockbroker and eventually a renowned financial investor.", 60));
            list.add(new ProductInfo(75, "Spirited Away", R.mipmap.img_75, 8.8, "Written and directed by Hayao Miyazaki, music by Joe Hisaishi, voiced by Rumi Hiiragi, Miyu Irino, Takeshi Naito, Mari Natsuki",
                    "Drama|Adventure|Fantasy|Animation|Family|Classic", "2001-07-20", "Japan", "The film tells the story of a man secretly imprisoned since the age of eight, unwilling to be merely a puppet or a weapon in someone else's hands. To break free and reclaim his true self, he must overcome countless challenges. The story revolves around this stand-in's struggle for freedom and the difficulties he encounters along the way.", 48));
            list.add(new ProductInfo(76, "Léon: The Professional", R.mipmap.img_76, 8.8, "Written and directed by Luc Besson, starring Natalie Portman, Jean Reno, Gary Oldman, Danny Aiello",
                    "Crime|Drama|Thriller|Classic", "1994-09-14", "France", "The film follows Léon, a professional hitman in New York's slums, who inadvertently saves Matilda, a rebellious girl whose family was massacred. They form a bond, developing feelings for each other, and together confront a corrupt cop, Stansfield.", 61));
            list.add(new ProductInfo(77, "The Imitation Game", R.mipmap.img_77, 8.6, "Directed by Morten Tyldum, written by Graham Moore and Andrew Hodges, starring Benedict Cumberbatch, Keira Knightley",
                    "Drama|Gay|Biography|War", "2014-12-25", "United States", "Adapted from Andrew Hodges' biography *Alan Turing: The Enigma*, the film chronicles the life of the 'father of computer science,' Alan Turing, focusing on his efforts to crack Germany's Enigma code during World War II, significantly impacting the war's outcome.", 50));
        } else if (position == 3) {
            list.add(new ProductInfo(80, "Aerial China", R.mipmap.img_80, 7.8, "Directed by Yu Le, Guo Ying",
                    "Documentary", "2017-01-28", "China", "Aerial China is a 34-episode aerial documentary produced by China Central Radio and Television, showcasing China's landscapes from above.", 23));
            list.add(new ProductInfo(81, "Dynasties", R.mipmap.img_81, 6.8, "Executive producer Mike Gunton",
                    "Documentary", "2018-11-12", "China", "Hailed as a milestone in BBC Earth's natural history series, Dynasties uses a 'unit drama' format to focus on five animals: chimpanzees on the edge of the Sahara Desert in Senegal, emperor penguins in Antarctica's polar wilderness, lions on Kenya's Maasai Mara savanna, painted wolves in Zimbabwe's Zambezi River floodplains, and tigers in India's Bandhavgarh jungle, revealing a world of power struggles and family betrayals.", 20));
            list.add(new ProductInfo(82, "Plants That Changed the World", R.mipmap.img_82, 7.8, "Directed by Li Chengcai, Zhou Ye",
                    "Documentary", "2019-09-13", "China", "This 10-episode series, covering Tea, Mulberry, Rice, Soybean, Medicinal Herbs, Bamboo, Fruits, Gardens, and Flowers, explores the life journeys of 21 plant species across 10 families and their impact on the world.", 27));
            list.add(new ProductInfo(83, "The Green Planet", R.mipmap.img_83, 8.8, "Directed by Paul Williams, Peter Bassett, Rosie Thomas, Elisabeth Oakham",
                    "Documentary", "2022-01-09", "China", "This series reveals the hidden and wondrous world of plants. It premiered on January 10, 2022, on CCTV-9's Global Vision program.", 20));
            list.add(new ProductInfo(84, "The Most Beautiful China", R.mipmap.img_84, 7.8, "Directed by Qiao Yan",
                    "Documentary", "2016-09-17", "China", "Using drone footage and cutting-edge VR technology, this documentary, filmed over a year, follows the 24 solar terms to showcase China's natural geography, traditional customs, and current events, telling stories of how the land nurtures its people.", 20));
            list.add(new ProductInfo(85, "Huaihai Campaign Revelation", R.mipmap.img_85, 7.8, "Directed by Dai Bo, Zhang Hao, Du Jun, Fan Jialiang, Xu Xiaowei, Lu Kun, Bai Di, Liu Yi",
                    "Documentary", "2019-10-05", "China", "Focusing on the Huaihai Campaign, one of the three major campaigns of the Chinese Civil War, this documentary delves into President Xi Jinping's 2017 speech at the Huaihai Campaign Memorial Hall, exploring the campaign's profound significance and contemporary value.", 20));
            list.add(new ProductInfo(86, "A Bite of China", R.mipmap.img_86, 9.8, "Directed by Chen Xiaoqing",
                    "Documentary", "2012-11-17", "China", "The program explores the Chinese pursuit of culinary excellence and a fulfilling life, weaving together stories of China's diverse food culture through real-life characters.", 20));
        } else if (position == 4) {
            list.add(new ProductInfo(90, "The Walking Dead", R.mipmap.img_90, 8.8, "Starring Andrew Lincoln, Norman Reedus, Lauren Cohan, Steven Yeun",
                    "Adventure|Drama|Horror|Thriller|Romance", "2010-10-13", "United States", "Adapted from Nanpai Sanshu's novel of the same name, the film follows Wu Xie, an enthusiast of ancient architecture, as he embarks on an unprecedented adventure under the guidance of his uncle, alongside Zhang Qiling, An Ning, Pan Zi, and Fatty Wang.", 40));
            list.add(new ProductInfo(91, "The Strain", R.mipmap.img_91, 8.7, "Directed by Guillermo del Toro, starring Corey Stoll, David Bradley, Mia Maestro, Sean Astin, Kevin Durand, Carlton Cuse",
                    "Drama|Sci-Fi|Horror", "2014-07-13", "United States", "The series follows a Boeing 777 that lands at JFK Airport with no signs of life or communication. A biothreat expert from the CDC investigates, discovering a new parasitic virus, leading to a vampire apocalypse as authorities lift the quarantine.", 50));
            list.add(new ProductInfo(92, "Breaking Bad", R.mipmap.img_92, 8.1, "Directed by Adam Bernstein, Michelle MacLaren, starring Bryan Cranston, Aaron Paul, Anna Gunn, Dean Norris, Betsy Brandt",
                    "Drama|Crime", "2008-08-20", "United States", "The series follows a high school chemistry teacher diagnosed with terminal cancer who uses his expertise to manufacture drugs, becoming a legendary drug kingpin to secure his family's future.", 30));
            list.add(new ProductInfo(93, "Money Heist", R.mipmap.img_93, 8.6, "Directed by Jesús Colmenar, Alejandro Bazzano, Miguel Ángel Vivas, Javier Quintas, Koldo Serra, starring Úrsula Corberó, Itziar Ituño, Álvaro Morte",
                    "Action|Thriller|Crime", "2017-05-02", "Spain", "The series follows a mastermind known as the Professor who assembles a team of skilled thieves for a meticulously planned heist involving dozens of hostages, vowing no harm will come to them.", 20));
            list.add(new ProductInfo(94, "Yellowstone", R.mipmap.img_94, 8.1, "Directed by Taylor Sheridan, starring Kevin Costner, Wes Bentley, Kelly Reilly, Luke Grimes",
                    "Drama|Western", "2018-06-20", "United States", "The series follows the Dutton family, whose ranch borders Yellowstone National Park, navigating boundary disputes in the American West.", 21));
            list.add(new ProductInfo(95, "Game of Thrones", R.mipmap.img_95, 8.2, "Directed by David Benioff, D.B. Weiss, Alan Taylor, written by David Benioff, D.B. Weiss, with George R.R. Martin as script consultant, starring Peter Dinklage, Lena Headey, Emilia Clarke, Kit Harington",
                    "Drama|War|Fantasy|Epic", "2011-04-17", "United States", "The story begins with the discovery of an extinct creature in Westeros, signaling impending danger. The Stark family of Winterfell, led by Lord Ned Stark, welcomes King Robert Baratheon, who seeks Ned's help as Hand of the King against rebels vying for the Iron Throne. Amidst brewing tensions, the Baratheon, Stark, Targaryen, and Lannister families navigate secrets and conflicts, with the king's sudden death plunging the realm into chaos.", 35));
            list.add(new ProductInfo(96, "Friends", R.mipmap.img_96, 8.4, "Created by David Crane, Marta Kauffman, directed by Kevin Bright, Gary Halvorson, Michael Lembeck, starring Jennifer Aniston, David Schwimmer, Courteney Cox, Lisa Kudrow, Matt LeBlanc, Matthew Perry",
                    "Comedy", "1994-09-24", "United States", "The series follows the daily lives of six best friends—Monica, Chandler, Rachel, Phoebe, Joey, and Ross—living together in New York, sharing stories of love, friendship, and humor.", 26));
            list.add(new ProductInfo(97, "Shameless", R.mipmap.img_97, 8.3, "Starring William H. Macy, Emmy Rossum, Jeremy Allen White, Cameron Monaghan",
                    "Drama|Family", "2011-01-09", "United States", "Adapted from the British series, this American version follows the lively Gallagher family, blending love, adventure, deception, and heartfelt moments in their daily lives.", 33));
        } else {
            list.add(new ProductInfo(101, "Half a Catty, Eight Taels", R.mipmap.img_101, 8.7, "Written, directed, and starring Michael Hui, co-starring Samuel Hui, Ricky Hui, Angie Chiu, Roy Chiao",
                    "Comedy", "1976-12-16", "Hong Kong, China", "The film follows the adventures of a stingy boss and his clever and dim-witted assistants at a private detective agency, handling minor cases like tracking affairs, debt collection, and catching thieves. The humorous journey ends with the assistants taking down a robbery gang, earning a partnership in the agency.", 40));
            list.add(new ProductInfo(102, "All's Well, Ends Well", R.mipmap.img_102, 7.9, "Directed by Clifton Ko, written by Vincent Kok, Teresa Tsui, Philip Cheng, Jerry Yang, starring Leslie Cheung, Stephen Chow, Maggie Cheung, Sandra Ng, Raymond Wong, Teresa Mo, Sheila Chan, Lee Heung-kam, Kwan Hoi-san",
                    "Drama|Comedy|Romance|Family", "1992-01-25", "Hong Kong, China", "The film depicts the lively and entertaining family life of the three Chang brothers—Chang Man, Chang Shu, and Chang Huan—each with distinct personalities.", 37));
            list.add(new ProductInfo(103, "Ashes of Time", R.mipmap.img_103, 8.8, "Written by Wong Kar-wai and Louis Cha, directed by Wong Kar-wai, starring Leslie Cheung, Brigitte Lin, Tony Leung Ka-fai, Tony Leung Chiu-wai",
                    "Drama|Action|Romance|Martial Arts|Costume", "2009-03-26", "Hong Kong, China", "Based on Louis Cha's *The Legend of the Condor Heroes*, the film follows young Ouyang Feng and Huang Yaoshi, two martial arts masters who become friends after a duel. Ouyang Feng's beloved marries his brother, leading him to retreat to a desert inn for a decade. The inn sees a parade of travelers, including old and new friends like the amnesiac Huang Yaoshi, the schizophrenic Murong Yan, a fallen blind warrior, the novice Hong Qigong, the conflicted Peach Blossom, and a resilient filial daughter. Eventually, Huang Yaoshi settles on Peach Blossom Island as the East Evil, while Ouyang Feng returns to White Camel Mountain as the West Poison.", 38));
            list.add(new ProductInfo(104, "Infernal Affairs", R.mipmap.img_104, 8.7, "Directed by Andrew Lau, Alan Mak, written by Alan Mak, Felix Chong, starring Andy Lau, Tony Leung, Anthony Wong, Eric Tsang",
                    "Drama|Crime|Thriller", "2002-12-12", "Hong Kong, China", "The film portrays two men with covert missions: one a police undercover agent, the other a mole in the triad. In a tense and complex era, they engage in psychological and strategic battles, navigating danger to discover their true identities and values, ultimately finding redemption and personal growth.", 42));
            list.add(new ProductInfo(105, "The Private Eyes", R.mipmap.img_105, 7.3, "Directed by Eric Tsang, Stanley Chow, Lau Kar-leung, starring Samuel Hui, Michael Miu, Joey Wong, with cameo appearances by Sammo Hung, Tsui Hark",
                    "Comedy|Action|Crime", "1982-04-15", "Hong Kong, China", "The story begins with master thief Black Cat leaving a white glove at a crime scene, leading police to suspect the international crime syndicate 'White Glove.' Interpol sends Detective Baldy to investigate, while the mafia dispatches a hitman to Hong Kong to probe the impostor. Feeling threatened, Black Cat turns himself in to the police, joining forces to take down the real 'White Glove.'", 40));
            list.add(new ProductInfo(106, "The Deer and the Cauldron", R.mipmap.img_106, 8.1, "Directed and written by Wong Jing, starring Stephen Chow, Sharla Cheung, Ng Man-tat, Sandra Ng, Damian Lau, Brigitte Lin, Chingmy Yau, Dicky Cheung, Nat Chan, Elvis Tsui",
                    "Comedy|Action|Martial Arts|Costume", "1992-07-30", "Hong Kong, China", "Adapted from Louis Cha's novel, this martial arts comedy follows Wei Xiaobao during the early Qing Dynasty, as the treacherous minister Oboi controls the young Emperor Kangxi. Wei joins the Heaven and Earth Society to overthrow the Qing, infiltrating the palace as an undercover agent to steal the secret-laden Forty-two Chapters Sutra. Befriending the emperor, Wei faces a dilemma between his mission and loyalty.", 48));
            list.add(new ProductInfo(107, "A Chinese Odyssey", R.mipmap.img_1071, 8.4, "Directed by Jeffrey Lau, starring Stephen Chow, Athena Chu, Ng Man-tat, Law Kar-ying, Karen Mok",
                    "Romance|Action|Fantasy|Adventure|Comedy|Tragedy", "1995-01-21", "Hong Kong, China", "The *A Chinese Odyssey* series, comprising *Pandora's Box* and *Cinderella*, tells a time-traveling tale of love, blending comedy and tragedy.", 45));
        }
        return list;
    }
}

